# Generated by Django 3.2.4 on 2023-03-29 14:45

from django.db import migrations, models
import jsonfield.fields
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', jsonfield.fields.JSONField(default=news.models.default_urls)),
                ('tags', models.ManyToManyField(blank=True, to='news.Tag', verbose_name='Tags')),
            ],
        ),
    ]
