# Generated by Django 3.2.4 on 2023-03-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0081_alter_itemdiscount_start_date'),
        ('game_studios', '0004_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
