# Generated by Django 3.2.4 on 2023-03-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_studios', '0006_auto_20230327_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.ImageField(blank=True, upload_to='game_studios/developers_images'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='image',
            field=models.ImageField(blank=True, upload_to='game_studios/publishers_images'),
        ),
    ]
