# Generated by Django 3.2.4 on 2023-03-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0060_auto_20230317_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
                ('item', models.ManyToManyField(to='products.Item')),
            ],
        ),
    ]
