# Generated by Django 3.2 on 2023-02-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_genre_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Tag',
        ),
    ]
