# Generated by Django 3.2 on 2023-02-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_genre_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='genres',
            new_name='tags',
        ),
    ]
