# Generated by Django 3.2 on 2023-02-17 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_auto_20230217_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='products.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
