# Generated by Django 3.2 on 2023-02-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
