# Generated by Django 3.2.4 on 2023-02-22 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0021_infavorites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InFavorites',
            new_name='Favorite',
        ),
    ]
