# Generated by Django 3.2.4 on 2023-02-23 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_itemrating_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.item'),
        ),
    ]
