# Generated by Django 3.2.4 on 2023-02-24 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_itemrating_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrating',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
