# Generated by Django 3.2.4 on 2023-02-28 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20230227_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('10%', 'Ten Percent'), ('20%', 'Twenty Percent'), ('30%', 'Thirty Percent'), ('50%', 'Fifty Percent'), ('80%', 'Eighty Percent')], max_length=20)),
                ('end_date', models.DateField(verbose_name=datetime.timedelta(0))),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.item')),
            ],
        ),
    ]
