# Generated by Django 3.2.4 on 2023-02-28 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_itemdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 11, 14, 40, 287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='end_date',
            field=models.CharField(choices=[('7 days, 0:00:00', '7 days'), ('14 days, 0:00:00', '14 days')], default='7 days, 0:00:00', max_length=30),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='value',
            field=models.CharField(choices=[('10', '10%'), ('20', '20%'), ('30', '30%'), ('50', '50%'), ('80', '80%')], max_length=20),
        ),
    ]
