# Generated by Django 3.2.4 on 2023-03-01 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20230228_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='end_date',
            field=models.CharField(choices=[('0:00:05', 'Test 5 seconds'), ('7 days, 0:00:00', '7 days'), ('14 days, 0:00:00', '14 days')], default='7 days, 0:00:00', max_length=30),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 9, 52, 15, 374968, tzinfo=utc)),
        ),
    ]
