# Generated by Django 3.2.4 on 2023-03-10 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_itemdiscount_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 10, 57, 17, 457232, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ItemPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item', models.ManyToManyField(to='products.Item')),
            ],
        ),
    ]
