# Generated by Django 3.2.4 on 2023-03-10 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20230310_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 11, 5, 38, 773325, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemplatform',
            name='item',
            field=models.ManyToManyField(related_name='platforms', to='products.Item'),
        ),
        migrations.AlterField(
            model_name='itemplatform',
            name='name',
            field=models.CharField(choices=[('Steam', 'Steam'), ('Xbox', 'Xbox'), ('Origin', 'Origin'), ('Uplay', 'Uplay'), ('Epic Games', 'Epic Games'), ('Unknown', 'Unknown')], default='Unknown', max_length=100),
        ),
    ]
