# Generated by Django 3.2.4 on 2023-03-10 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20230310_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemplatform',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 12, 36, 38, 483858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemplatform',
            name='name',
            field=models.CharField(choices=[('Steam', 'Steam'), ('Xbox', 'Xbox'), ('Rockstar Games', 'Rockstar Games'), ('Uplay', 'Uplay'), ('Epic Games', 'Epic Games'), ('Unknown', 'Unknown')], default='Unknown', max_length=100),
        ),
    ]
