# Generated by Django 3.2.4 on 2023-03-10 13:05

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20230310_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 13, 5, 54, 458403, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemplatform',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])]),
        ),
    ]
