# Generated by Django 3.2.4 on 2023-03-10 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20230310_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 13, 46, 37, 700877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemplatform',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
