# Generated by Django 3.2.4 on 2023-03-10 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_alter_itemdiscount_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='trailer',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 14, 40, 24, 150612, tzinfo=utc)),
        ),
    ]
