# Generated by Django 3.2.4 on 2023-03-14 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20230310_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 14, 37, 50, 578669, tzinfo=utc)),
        ),
    ]
