# Generated by Django 3.2.4 on 2023-03-15 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_auto_20230315_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 13, 55, 58, 54374, tzinfo=utc)),
        ),
    ]
