# Generated by Django 3.2.4 on 2023-03-15 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_auto_20230315_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 14, 38, 27, 38213, tzinfo=utc)),
        ),
    ]
