# Generated by Django 3.2.4 on 2023-03-16 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_auto_20230316_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 13, 27, 54, 753593, tzinfo=utc)),
        ),
    ]
