# Generated by Django 3.2.4 on 2023-03-17 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_auto_20230317_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 13, 40, 48, 46419, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
