# Generated by Django 3.2.4 on 2023-03-22 18:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_auto_20230321_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tagline',
            field=models.CharField(default='Game is coming', max_length=150, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 18, 0, 5, 877794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdlc',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.item', verbose_name='Game'),
        ),
    ]
