# Generated by Django 3.2.4 on 2023-03-22 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_auto_20230322_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 18, 5, 48, 330792, tzinfo=utc)),
        ),
    ]
