# Generated by Django 3.2.4 on 2023-03-23 12:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_alter_itemdiscount_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('English', 'English'), ('Russian', 'Russian'), ('German', 'German'), ('Spanish', 'Spanish'), ('French', 'French'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Chinese', 'Chinese')], default='English', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 12, 5, 33, 195264, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ItemLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.BooleanField(default=0, verbose_name='Interface')),
                ('subtitles', models.BooleanField(default=0, verbose_name='Subtitles')),
                ('voice_acting', models.BooleanField(default=0, verbose_name='Voice acting')),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.language', verbose_name='Language')),
            ],
        ),
    ]
