# Generated by Django 3.2.4 on 2023-03-23 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_auto_20230323_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlocalization',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.item'),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 12, 10, 17, 244308, tzinfo=utc)),
        ),
    ]
