# Generated by Django 3.2.4 on 2023-03-23 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_auto_20230323_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 12, 20, 29, 176749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemlocalization',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='products.language', verbose_name='Language'),
        ),
    ]
