# Generated by Django 3.2.4 on 2023-03-23 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_auto_20230323_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 13, 8, 33, 16667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minimalsystemrequirements',
            name='graphics_card',
            field=models.CharField(default='NVIDIA or AMD', max_length=150, verbose_name='Graphics card'),
        ),
        migrations.AlterField(
            model_name='minimalsystemrequirements',
            name='ram',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (6, '6'), (8, '8'), (12, '12'), (16, '16')], default=4, max_length=150, verbose_name='RAM'),
        ),
    ]
