# Generated by Django 3.2.4 on 2023-03-23 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_auto_20230323_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minimalsystemrequirements',
            old_name='oc',
            new_name='os',
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 13, 14, 3, 699096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minimalsystemrequirements',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='minimal_system_requirements', to='products.item'),
        ),
    ]
