# Generated by Django 3.2.4 on 2023-03-23 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_auto_20230323_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 13, 45, 8, 989078, tzinfo=utc)),
        ),
    ]
