# Generated by Django 3.2.4 on 2023-03-23 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_alter_itemdiscount_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 14, 38, 48, 715763, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='RegionOfActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Russia, Ukraine and CIS', 'Cis'), ('Europe', 'Europe'), ('USA', 'Usa')], default='Russia, Ukraine and CIS', max_length=50, verbose_name='Region of activation')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='products.item')),
            ],
        ),
    ]
