# Generated by Django 3.2.4 on 2023-03-23 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_auto_20230323_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 15, 2, 9, 992212, tzinfo=utc)),
        ),
    ]
