# Generated by Django 3.2.4 on 2023-03-24 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0079_auto_20230323_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 13, 38, 17, 246916, tzinfo=utc)),
        ),
    ]
