# Generated by Django 3.2.4 on 2023-03-24 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game_studios', '0005_auto_20230324_1541'),
        ('products', '0082_auto_20230324_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='developer',
            field=models.ManyToManyField(to='game_studios.Developer'),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 14, 57, 14, 374687, tzinfo=utc)),
        ),
    ]
