# Generated by Django 3.2.4 on 2023-03-28 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0086_auto_20230327_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 15, 32, 22, 323485, tzinfo=utc)),
        ),
    ]
