# Generated by Django 3.2.4 on 2023-04-03 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0088_alter_itemdiscount_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='trailer',
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 11, 32, 1, 703864, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='GameTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='products.item')),
            ],
        ),
    ]
