# Generated by Django 3.2.4 on 2023-04-03 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0089_auto_20230403_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 12, 9, 59, 111294, tzinfo=utc)),
        ),
    ]
