# Generated by Django 3.2.4 on 2023-04-03 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0090_alter_itemdiscount_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=124)),
            ],
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 13, 18, 1, 763906, tzinfo=utc)),
        ),
    ]
