# Generated by Django 3.2.4 on 2023-04-04 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0092_alter_itemdiscount_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='genre',
            field=models.ManyToManyField(to='products.Genre', verbose_name='Game genres'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='products.Tag', verbose_name='Game tags'),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 10, 44, 0, 146991, tzinfo=utc)),
        ),
    ]
