# Generated by Django 3.2.4 on 2023-04-05 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0093_auto_20230404_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 15, 29, 35, 497444, tzinfo=utc)),
        ),
    ]
