# Generated by Django 3.2.4 on 2023-04-05 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0094_alter_itemdiscount_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 15, 49, 52, 412425, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.item')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='products.item')),
            ],
            bases=('products.item',),
        ),
    ]
