# Generated by Django 3.2.4 on 2023-04-05 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0095_auto_20230405_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Game', 'Game'), ('DLC', 'Addon')], default='Game', max_length=15),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 16, 27, 6, 646454, tzinfo=utc)),
        ),
    ]
