# Generated by Django 3.2.4 on 2023-04-06 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0096_auto_20230405_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parent_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.item'),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 9, 55, 34, 887679, tzinfo=utc)),
        ),
    ]
