# Generated by Django 3.2.4 on 2023-04-12 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0099_auto_20230407_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item',
            name='parent_game',
        ),
        migrations.AddField(
            model_name='item',
            name='parent_game',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.item', verbose_name="Parent game (if it's a DLC)"),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 12, 5, 26, 45164, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ItemDLC',
        ),
    ]
