# Generated by Django 3.2.4 on 2023-04-12 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0100_auto_20230412_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='parent_game',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 12, 9, 48, 323156, tzinfo=utc)),
        ),
    ]
