# Generated by Django 3.2.4 on 2023-04-12 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0101_auto_20230412_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 15, 37, 57, 737267, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='item',
            name='series',
            field=models.ManyToManyField(to='products.Series', verbose_name='Series'),
        ),
    ]
