# Generated by Django 3.2.4 on 2023-04-12 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0102_auto_20230412_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='series',
            field=models.ManyToManyField(blank=True, to='products.Series', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 15, 38, 10, 415138, tzinfo=utc)),
        ),
    ]
