# Generated by Django 3.2.4 on 2023-04-12 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0103_auto_20230412_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/series_screenshots'),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 15, 39, 22, 540577, tzinfo=utc)),
        ),
    ]
