# Generated by Django 3.2.4 on 2023-04-13 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0105_auto_20230412_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='series',
        ),
        migrations.AddField(
            model_name='item',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.series', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 15, 0, 19, 743927, tzinfo=utc)),
        ),
    ]
