# Generated by Django 3.2.4 on 2024-06-11 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0106_auto_20230413_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 21, 51, 40, 262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minimalsystemrequirements',
            name='graphics_card',
            field=models.CharField(default='No data', max_length=150, verbose_name='Graphics card'),
        ),
        migrations.AlterField(
            model_name='minimalsystemrequirements',
            name='os',
            field=models.CharField(default='No data', max_length=50, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='minimalsystemrequirements',
            name='processor',
            field=models.CharField(default='No data', max_length=60, verbose_name='Processor'),
        ),
    ]
